[Thu Feb 14 07:42:28.394232 2019] [ssl:warn] [pid 19398] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:42:28.394259 2019] [ssl:warn] [pid 19398] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:42:28.422739 2019] [ssl:warn] [pid 19412] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:42:28.422762 2019] [ssl:warn] [pid 19412] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:42:57.244863 2019] [authz_core:error] [pid 19444] [client 198.182.56.5:10421] AH01630: client denied by server configuration: /opt/django_sites/pegasus
[Thu Feb 14 07:42:57.436154 2019] [authz_core:error] [pid 19445] [client 198.182.56.5:10422] AH01630: client denied by server configuration: /opt/django_sites/pegasus
[Thu Feb 14 07:44:24.705656 2019] [ssl:warn] [pid 19473] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:44:24.705687 2019] [ssl:warn] [pid 19473] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:44:24.733421 2019] [ssl:warn] [pid 19477] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:44:24.733441 2019] [ssl:warn] [pid 19477] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:47:20.343997 2019] [ssl:warn] [pid 19563] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:47:20.344022 2019] [ssl:warn] [pid 19563] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:47:20.373832 2019] [ssl:warn] [pid 19576] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:47:20.373855 2019] [ssl:warn] [pid 19576] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:53:45.398371 2019] [ssl:warn] [pid 19651] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:53:45.398391 2019] [ssl:warn] [pid 19651] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:53:45.427832 2019] [ssl:warn] [pid 19655] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:53:45.427856 2019] [ssl:warn] [pid 19655] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:57:36.282369 2019] [ssl:warn] [pid 19707] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:57:36.282389 2019] [ssl:warn] [pid 19707] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:57:36.310282 2019] [ssl:warn] [pid 19711] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:57:36.310302 2019] [ssl:warn] [pid 19711] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:59:06.471755 2019] [ssl:warn] [pid 19749] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:59:06.471803 2019] [ssl:warn] [pid 19749] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 07:59:06.500729 2019] [ssl:warn] [pid 19751] AH01906: pegasus:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 07:59:06.501300 2019] [ssl:warn] [pid 19751] AH01909: pegasus:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 09:26:44.547651 2019] [ssl:warn] [pid 826] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 09:26:44.548153 2019] [ssl:warn] [pid 826] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 09:26:44.921898 2019] [ssl:warn] [pid 1007] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 09:26:44.921923 2019] [ssl:warn] [pid 1007] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 20:56:49.617415 2019] [ssl:warn] [pid 15985] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 20:56:49.617454 2019] [ssl:warn] [pid 15985] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 20:56:49.652341 2019] [ssl:warn] [pid 15988] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 20:56:49.652361 2019] [ssl:warn] [pid 15988] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 20:57:05.409307 2019] [wsgi:error] [pid 15993] [remote 130.212.92.99:31672] Invalid HTTP_HOST header: 'pegasus'. You may need to add 'pegasus' to ALLOWED_HOSTS.
[Thu Feb 14 20:57:05.441407 2019] [wsgi:error] [pid 15993] [remote 130.212.92.99:31672] Bad Request: /web/
[Thu Feb 14 20:58:25.509448 2019] [ssl:warn] [pid 16076] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 20:58:25.509522 2019] [ssl:warn] [pid 16076] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 20:58:25.538091 2019] [ssl:warn] [pid 16078] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 20:58:25.538116 2019] [ssl:warn] [pid 16078] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 20:58:31.192459 2019] [wsgi:error] [pid 16083] [remote 130.212.92.99:53826] Not Found: /web/
[Thu Feb 14 20:59:52.321915 2019] [wsgi:error] [pid 16083] [remote 130.212.92.99:15534] Not Found: /web/
[Thu Feb 14 21:01:49.293824 2019] [wsgi:error] [pid 16083] [remote 130.212.92.99:17577] Not Found: /web/
[Thu Feb 14 23:20:34.557546 2019] [ssl:warn] [pid 19074] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 23:20:34.557588 2019] [ssl:warn] [pid 19074] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 23:20:34.585976 2019] [ssl:warn] [pid 19076] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 14 23:20:34.585997 2019] [ssl:warn] [pid 19076] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:10:27.836483 2019] [wsgi:error] [pid 19081] [remote 76.102.91.96:61060] Not Found: /web/
[Fri Feb 15 03:10:31.530863 2019] [wsgi:error] [pid 19081] [remote 76.102.91.96:61060] Not Found: /web/about
[Fri Feb 15 03:11:15.131745 2019] [ssl:warn] [pid 24025] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:11:15.131800 2019] [ssl:warn] [pid 24025] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:11:15.159820 2019] [ssl:warn] [pid 24026] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:11:15.159842 2019] [ssl:warn] [pid 24026] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 14 19:12:23.762267 2019] [wsgi:error] [pid 24031] [remote 76.102.91.96:61120] Not Found: /web/
[Fri Feb 15 03:16:05.807706 2019] [ssl:warn] [pid 24432] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:16:05.807757 2019] [ssl:warn] [pid 24432] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:16:05.837394 2019] [ssl:warn] [pid 24433] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:16:05.837418 2019] [ssl:warn] [pid 24433] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:22:17.354808 2019] [ssl:warn] [pid 24620] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:22:17.354857 2019] [ssl:warn] [pid 24620] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:22:17.382959 2019] [ssl:warn] [pid 24622] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:22:17.382982 2019] [ssl:warn] [pid 24622] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:44:00.731006 2019] [ssl:warn] [pid 25491] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:44:00.731054 2019] [ssl:warn] [pid 25491] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 03:44:00.759810 2019] [ssl:warn] [pid 25494] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 03:44:00.759834 2019] [ssl:warn] [pid 25494] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Feb 15 06:25:02.652174 2019] [ssl:warn] [pid 25494] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Fri Feb 15 06:25:02.652215 2019] [ssl:warn] [pid 25494] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Feb 16 06:25:02.762087 2019] [ssl:warn] [pid 25494] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Feb 16 06:25:02.762629 2019] [ssl:warn] [pid 25494] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Feb 16 22:20:31.004179 2019] [ssl:warn] [pid 7446] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Feb 16 22:20:31.004231 2019] [ssl:warn] [pid 7446] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Feb 16 22:20:31.066575 2019] [ssl:warn] [pid 7457] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Feb 16 22:20:31.066607 2019] [ssl:warn] [pid 7457] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Feb 16 22:24:47.559167 2019] [ssl:warn] [pid 7611] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Feb 16 22:24:47.559217 2019] [ssl:warn] [pid 7611] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Feb 16 22:24:47.588187 2019] [ssl:warn] [pid 7613] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Feb 16 22:24:47.588211 2019] [ssl:warn] [pid 7613] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Feb 17 06:25:02.710795 2019] [ssl:warn] [pid 7613] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Feb 17 06:25:02.712161 2019] [ssl:warn] [pid 7613] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 18 00:28:10.949228 2019] [ssl:warn] [pid 5421] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Feb 18 00:28:10.949279 2019] [ssl:warn] [pid 5421] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 18 00:28:11.003944 2019] [ssl:warn] [pid 5423] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Feb 18 00:28:11.003977 2019] [ssl:warn] [pid 5423] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Feb 18 06:25:02.781289 2019] [ssl:warn] [pid 5423] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Feb 18 06:25:02.781325 2019] [ssl:warn] [pid 5423] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Feb 19 06:25:03.298495 2019] [ssl:warn] [pid 5423] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Feb 19 06:25:03.298527 2019] [ssl:warn] [pid 5423] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 20 06:25:01.815915 2019] [ssl:warn] [pid 5423] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Feb 20 06:25:01.815945 2019] [ssl:warn] [pid 5423] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 02:58:32.935565 2019] [ssl:warn] [pid 4638] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 02:58:32.936563 2019] [ssl:warn] [pid 4638] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 02:58:32.965891 2019] [ssl:warn] [pid 4639] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 02:58:32.965916 2019] [ssl:warn] [pid 4639] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 02:59:34.249303 2019] [ssl:warn] [pid 4743] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 02:59:34.249361 2019] [ssl:warn] [pid 4743] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 02:59:34.278076 2019] [ssl:warn] [pid 4745] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 02:59:34.278099 2019] [ssl:warn] [pid 4745] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 03:01:35.712944 2019] [ssl:warn] [pid 4856] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 03:01:35.712992 2019] [ssl:warn] [pid 4856] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 03:01:35.741390 2019] [ssl:warn] [pid 4858] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 03:01:35.741412 2019] [ssl:warn] [pid 4858] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 03:19:20.226047 2019] [ssl:warn] [pid 6126] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 03:19:20.226543 2019] [ssl:warn] [pid 6126] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 03:19:20.286865 2019] [ssl:warn] [pid 6130] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 03:19:20.286900 2019] [ssl:warn] [pid 6130] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 20 19:19:28.423468 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:36660] Not Found: /web/quan/images/img1.png
[Wed Feb 20 19:20:31.732647 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] Internal Server Error: /web/fatma/
[Wed Feb 20 19:20:31.732675 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] Traceback (most recent call last):
[Wed Feb 20 19:20:31.732680 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Wed Feb 20 19:20:31.732684 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     compile_func = self.tags[command]
[Wed Feb 20 19:20:31.732687 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] KeyError: 'static'
[Wed Feb 20 19:20:31.732690 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] 
[Wed Feb 20 19:20:31.732694 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] During handling of the above exception, another exception occurred:
[Wed Feb 20 19:20:31.732697 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] 
[Wed Feb 20 19:20:31.732701 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] Traceback (most recent call last):
[Wed Feb 20 19:20:31.732704 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Wed Feb 20 19:20:31.732708 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     response = get_response(request)
[Wed Feb 20 19:20:31.732711 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Wed Feb 20 19:20:31.732726 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     response = self.process_exception_by_middleware(e, request)
[Wed Feb 20 19:20:31.732730 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Wed Feb 20 19:20:31.732733 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Feb 20 19:20:31.732736 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/about/views.py", line 13, in fatma
[Wed Feb 20 19:20:31.732739 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     return render(request, 'about/fatma.html')
[Wed Feb 20 19:20:31.732742 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Wed Feb 20 19:20:31.732745 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     content = loader.render_to_string(template_name, context, request, using=using)
[Wed Feb 20 19:20:31.732748 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Wed Feb 20 19:20:31.732751 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     template = get_template(template_name, using=using)
[Wed Feb 20 19:20:31.732754 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Wed Feb 20 19:20:31.732757 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     return engine.get_template(template_name)
[Wed Feb 20 19:20:31.732760 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Wed Feb 20 19:20:31.732763 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     return Template(self.engine.get_template(template_name), self)
[Wed Feb 20 19:20:31.732766 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Wed Feb 20 19:20:31.732769 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     template, origin = self.find_template(template_name)
[Wed Feb 20 19:20:31.732772 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Wed Feb 20 19:20:31.732775 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     template = loader.get_template(name, skip=skip)
[Wed Feb 20 19:20:31.732778 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Wed Feb 20 19:20:31.732781 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     contents, origin, origin.template_name, self.engine,
[Wed Feb 20 19:20:31.732784 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Wed Feb 20 19:20:31.732787 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     self.nodelist = self.compile_nodelist()
[Wed Feb 20 19:20:31.732790 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Wed Feb 20 19:20:31.732796 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     return parser.parse()
[Wed Feb 20 19:20:31.732799 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Wed Feb 20 19:20:31.732802 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     self.invalid_block_tag(token, command, parse_until)
[Wed Feb 20 19:20:31.732805 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Wed Feb 20 19:20:31.732809 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503]     "or load this tag?" % (token.lineno, command)
[Wed Feb 20 19:20:31.732813 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 14: 'static'. Did you forget to register or load this tag?
[Wed Feb 20 19:20:31.732818 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:58503] 
[Wed Feb 20 19:20:57.966155 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:52312] Not Found: /web/fatma/images/pet.jpg
[Wed Feb 20 19:21:02.932943 2019] [wsgi:error] [pid 6133] [remote 130.212.94.231:52312] Not Found: /web/wafi/images/wafless.jpg
[Thu Feb 21 03:24:11.458836 2019] [ssl:warn] [pid 6308] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 03:24:11.458883 2019] [ssl:warn] [pid 6308] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 03:24:11.487233 2019] [ssl:warn] [pid 6310] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 03:24:11.487258 2019] [ssl:warn] [pid 6310] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Feb 21 03:37:16.402097 2019] [php7:warn] [pid 6342] [client 130.212.94.231:51958] PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;admin&quot;\nFATAL:  password authentication failed for user &quot;admin&quot; in /usr/share/php/adodb/drivers/adodb-postgres64.inc.php on line 727, referer: https://pegasus/phppgadmin/redirect.php?subject=server&server=localhost%3A5432%3Aallow
[Thu Feb 21 06:25:03.044854 2019] [ssl:warn] [pid 6310] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Feb 21 06:25:03.044892 2019] [ssl:warn] [pid 6310] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Mar 23 17:00:07.667685 2019] [ssl:warn] [pid 18015:tid 140650732661696] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Mar 23 17:00:07.667709 2019] [ssl:warn] [pid 18015:tid 140650732661696] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Mar 23 17:00:07.672804 2019] [ssl:warn] [pid 18016:tid 140650732661696] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sat Mar 23 17:00:07.672818 2019] [ssl:warn] [pid 18016:tid 140650732661696] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 13:44:31.589571 2019] [ssl:warn] [pid 970:tid 140219765562304] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 13:44:31.589984 2019] [ssl:warn] [pid 970:tid 140219765562304] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 13:44:31.598659 2019] [ssl:warn] [pid 1050:tid 140219765562304] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 13:44:31.598686 2019] [ssl:warn] [pid 1050:tid 140219765562304] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 15:17:32.395778 2019] [wsgi:error] [pid 1051:tid 140219637286656] [remote 127.0.0.1:37024] Not Found: /web/demo/like_button.js
[Sun Mar 24 15:17:32.659149 2019] [wsgi:error] [pid 1051:tid 140219536574208] [remote 127.0.0.1:37024] Not Found: /web/demo/like_button.js
[Sun Mar 24 15:19:32.454201 2019] [wsgi:error] [pid 1051:tid 140219536574208] [remote 127.0.0.1:37042] Not Found: /web/demo/static/demo/like_button.js
[Sun Mar 24 15:19:32.780754 2019] [wsgi:error] [pid 1051:tid 140219637286656] [remote 127.0.0.1:37042] Not Found: /web/demo/static/demo/like_button.js
[Sun Mar 24 15:19:33.583721 2019] [wsgi:error] [pid 1051:tid 140219637286656] [remote 127.0.0.1:37042] Not Found: /web/demo/static/demo/like_button.js
[Sun Mar 24 15:19:33.871335 2019] [wsgi:error] [pid 1051:tid 140219536574208] [remote 127.0.0.1:37042] Not Found: /web/demo/static/demo/like_button.js
[Sun Mar 24 18:51:43.349432 2019] [ssl:warn] [pid 946:tid 140284486052800] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 18:51:43.349460 2019] [ssl:warn] [pid 946:tid 140284486052800] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 18:51:43.360824 2019] [ssl:warn] [pid 1024:tid 140284486052800] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 18:51:43.360837 2019] [ssl:warn] [pid 1024:tid 140284486052800] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 19:25:29.150622 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38436] Not Found: /web/demo/demo/static 'demo/like_button.js'
[Sun Mar 24 19:25:29.408465 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38436] Not Found: /web/demo/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:54.314993 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:54.658553 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:55.565439 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:55.938198 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:56.499285 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:56.807942 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:56.950748 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38462] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:56.981674 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38460] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:57.416609 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38460] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:57.448351 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38466] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:26:57.760261 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38466] Not Found: /web/demo/static 'demo/like_button.js'
[Sun Mar 24 19:28:34.757803 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:35.056380 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:36.088563 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:36.473054 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:36.652483 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:36.952575 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:37.029614 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:28:37.432687 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38550] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:29:05.015106 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38560] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:29:05.327082 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38560] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:29:43.384392 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38566] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:29:43.708629 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38566] Not Found: /web/demo/{ static 'demo/like_button.js'}
[Sun Mar 24 19:36:11.273997 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38614] Not Found: /web/demo/{ static 'like_button.js'}
[Sun Mar 24 19:36:11.583372 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38614] Not Found: /web/demo/{ static 'like_button.js'}
[Sun Mar 24 19:41:19.704190 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38862] Not Found: /web/demo/{ static 'like_button.js'}
[Sun Mar 24 19:41:20.113495 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38862] Not Found: /web/demo/{ static 'like_button.js'}
[Sun Mar 24 19:41:24.850216 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:38862] Not Found: /web/demo/{ static 'like_button.js'}
[Sun Mar 24 19:41:26.026367 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:38862] Not Found: /web/demo/{ static 'like_button.js'}
[Sun Mar 24 19:57:24.115756 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] Internal Server Error: /web/demo/
[Sun Mar 24 19:57:24.115777 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] Traceback (most recent call last):
[Sun Mar 24 19:57:24.115780 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 19:57:24.115783 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     compile_func = self.tags[command]
[Sun Mar 24 19:57:24.115785 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] KeyError: 'static'
[Sun Mar 24 19:57:24.115788 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] 
[Sun Mar 24 19:57:24.115790 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] During handling of the above exception, another exception occurred:
[Sun Mar 24 19:57:24.115797 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] 
[Sun Mar 24 19:57:24.115800 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] Traceback (most recent call last):
[Sun Mar 24 19:57:24.115802 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 19:57:24.115804 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     response = get_response(request)
[Sun Mar 24 19:57:24.115806 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 19:57:24.115808 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 19:57:24.115810 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 19:57:24.115813 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 19:57:24.115815 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 19:57:24.115817 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 19:57:24.115819 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 19:57:24.115821 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 19:57:24.115823 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 19:57:24.115826 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     template = get_template(template_name, using=using)
[Sun Mar 24 19:57:24.115828 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 19:57:24.115830 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     return engine.get_template(template_name)
[Sun Mar 24 19:57:24.115832 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 19:57:24.115834 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 19:57:24.115836 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 19:57:24.115838 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     template, origin = self.find_template(template_name)
[Sun Mar 24 19:57:24.115840 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 19:57:24.115844 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 19:57:24.115847 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 19:57:24.115849 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 19:57:24.115851 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 19:57:24.115853 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 19:57:24.115855 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 19:57:24.115857 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     return parser.parse()
[Sun Mar 24 19:57:24.115859 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 19:57:24.115861 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 19:57:24.115863 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 19:57:24.115866 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 19:57:24.115869 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 19:57:24.115873 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39276] 
[Sun Mar 24 19:58:55.777670 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] Internal Server Error: /web/demo/
[Sun Mar 24 19:58:55.777691 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] Traceback (most recent call last):
[Sun Mar 24 19:58:55.777694 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 19:58:55.777697 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     compile_func = self.tags[command]
[Sun Mar 24 19:58:55.777699 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] KeyError: 'static'
[Sun Mar 24 19:58:55.777702 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] 
[Sun Mar 24 19:58:55.777704 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] During handling of the above exception, another exception occurred:
[Sun Mar 24 19:58:55.777706 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] 
[Sun Mar 24 19:58:55.777709 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] Traceback (most recent call last):
[Sun Mar 24 19:58:55.777711 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 19:58:55.777714 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     response = get_response(request)
[Sun Mar 24 19:58:55.777722 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 19:58:55.777724 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 19:58:55.777726 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 19:58:55.777728 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 19:58:55.777731 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 19:58:55.777733 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 19:58:55.777735 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 19:58:55.777737 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 19:58:55.777739 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 19:58:55.777742 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     template = get_template(template_name, using=using)
[Sun Mar 24 19:58:55.777744 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 19:58:55.777746 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     return engine.get_template(template_name)
[Sun Mar 24 19:58:55.777748 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 19:58:55.777750 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 19:58:55.777752 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 19:58:55.777754 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     template, origin = self.find_template(template_name)
[Sun Mar 24 19:58:55.777756 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 19:58:55.777759 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 19:58:55.777761 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 19:58:55.777763 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 19:58:55.777767 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 19:58:55.777769 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 19:58:55.777771 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 19:58:55.777773 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     return parser.parse()
[Sun Mar 24 19:58:55.777775 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 19:58:55.777778 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 19:58:55.777780 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 19:58:55.777782 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 19:58:55.777785 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 19:58:55.777789 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39282] 
[Sun Mar 24 20:03:04.473518 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] Internal Server Error: /web/demo/
[Sun Mar 24 20:03:04.473539 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] Traceback (most recent call last):
[Sun Mar 24 20:03:04.473542 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 20:03:04.473545 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     compile_func = self.tags[command]
[Sun Mar 24 20:03:04.473547 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] KeyError: 'static'
[Sun Mar 24 20:03:04.473550 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] 
[Sun Mar 24 20:03:04.473552 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] During handling of the above exception, another exception occurred:
[Sun Mar 24 20:03:04.473554 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] 
[Sun Mar 24 20:03:04.473557 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] Traceback (most recent call last):
[Sun Mar 24 20:03:04.473559 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 20:03:04.473562 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     response = get_response(request)
[Sun Mar 24 20:03:04.473564 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 20:03:04.473566 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 20:03:04.473569 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 20:03:04.473577 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 20:03:04.473579 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 20:03:04.473581 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 20:03:04.473583 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 20:03:04.473586 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 20:03:04.473588 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 20:03:04.473590 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     template = get_template(template_name, using=using)
[Sun Mar 24 20:03:04.473592 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 20:03:04.473594 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     return engine.get_template(template_name)
[Sun Mar 24 20:03:04.473596 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 20:03:04.473599 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 20:03:04.473601 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 20:03:04.473603 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     template, origin = self.find_template(template_name)
[Sun Mar 24 20:03:04.473605 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 20:03:04.473607 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 20:03:04.473609 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 20:03:04.473611 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 20:03:04.473614 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 20:03:04.473617 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 20:03:04.473620 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 20:03:04.473623 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     return parser.parse()
[Sun Mar 24 20:03:04.473629 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 20:03:04.473632 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 20:03:04.473634 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 20:03:04.473637 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 20:03:04.473641 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 20:03:04.473647 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39316] 
[Sun Mar 24 20:07:29.693086 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] Internal Server Error: /web/demo/
[Sun Mar 24 20:07:29.693139 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] Traceback (most recent call last):
[Sun Mar 24 20:07:29.693143 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 20:07:29.693146 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     compile_func = self.tags[command]
[Sun Mar 24 20:07:29.693149 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] KeyError: 'static'
[Sun Mar 24 20:07:29.693151 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] 
[Sun Mar 24 20:07:29.693154 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] During handling of the above exception, another exception occurred:
[Sun Mar 24 20:07:29.693156 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] 
[Sun Mar 24 20:07:29.693158 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] Traceback (most recent call last):
[Sun Mar 24 20:07:29.693161 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 20:07:29.693164 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     response = get_response(request)
[Sun Mar 24 20:07:29.693166 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 20:07:29.693169 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 20:07:29.693172 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 20:07:29.693174 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 20:07:29.693177 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 20:07:29.693196 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 20:07:29.693206 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 20:07:29.693208 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 20:07:29.693210 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 20:07:29.693213 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     template = get_template(template_name, using=using)
[Sun Mar 24 20:07:29.693215 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 20:07:29.693217 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     return engine.get_template(template_name)
[Sun Mar 24 20:07:29.693219 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 20:07:29.693221 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 20:07:29.693223 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 20:07:29.693226 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     template, origin = self.find_template(template_name)
[Sun Mar 24 20:07:29.693228 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 20:07:29.693230 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 20:07:29.693232 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 20:07:29.693234 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 20:07:29.693236 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 20:07:29.693238 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 20:07:29.693240 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 20:07:29.693243 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     return parser.parse()
[Sun Mar 24 20:07:29.693245 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 20:07:29.693247 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 20:07:29.693249 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 20:07:29.693253 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 20:07:29.693256 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 20:07:29.693261 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39626] 
[Sun Mar 24 20:07:31.649055 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] Internal Server Error: /web/demo/
[Sun Mar 24 20:07:31.649075 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] Traceback (most recent call last):
[Sun Mar 24 20:07:31.649078 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 20:07:31.649081 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     compile_func = self.tags[command]
[Sun Mar 24 20:07:31.649083 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] KeyError: 'static'
[Sun Mar 24 20:07:31.649085 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] 
[Sun Mar 24 20:07:31.649087 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] During handling of the above exception, another exception occurred:
[Sun Mar 24 20:07:31.649089 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] 
[Sun Mar 24 20:07:31.649091 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] Traceback (most recent call last):
[Sun Mar 24 20:07:31.649093 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 20:07:31.649095 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     response = get_response(request)
[Sun Mar 24 20:07:31.649097 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 20:07:31.649099 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 20:07:31.649102 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 20:07:31.649104 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 20:07:31.649106 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 20:07:31.649108 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 20:07:31.649110 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 20:07:31.649113 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 20:07:31.649115 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 20:07:31.649124 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     template = get_template(template_name, using=using)
[Sun Mar 24 20:07:31.649126 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 20:07:31.649129 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     return engine.get_template(template_name)
[Sun Mar 24 20:07:31.649131 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 20:07:31.649133 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 20:07:31.649135 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 20:07:31.649137 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     template, origin = self.find_template(template_name)
[Sun Mar 24 20:07:31.649139 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 20:07:31.649142 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 20:07:31.649144 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 20:07:31.649146 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 20:07:31.649148 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 20:07:31.649150 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 20:07:31.649152 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 20:07:31.649154 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     return parser.parse()
[Sun Mar 24 20:07:31.649157 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 20:07:31.649159 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 20:07:31.649161 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 20:07:31.649163 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 20:07:31.649166 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 20:07:31.649170 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39632] 
[Sun Mar 24 20:07:45.421350 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] Internal Server Error: /web/demo/
[Sun Mar 24 20:07:45.421375 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] Traceback (most recent call last):
[Sun Mar 24 20:07:45.421377 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 20:07:45.421380 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     compile_func = self.tags[command]
[Sun Mar 24 20:07:45.421382 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] KeyError: 'static'
[Sun Mar 24 20:07:45.421384 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] 
[Sun Mar 24 20:07:45.421386 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] During handling of the above exception, another exception occurred:
[Sun Mar 24 20:07:45.421388 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] 
[Sun Mar 24 20:07:45.421390 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] Traceback (most recent call last):
[Sun Mar 24 20:07:45.421392 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 20:07:45.421395 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     response = get_response(request)
[Sun Mar 24 20:07:45.421397 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 20:07:45.421399 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 20:07:45.421401 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 20:07:45.421403 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 20:07:45.421405 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 20:07:45.421408 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 20:07:45.421410 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 20:07:45.421412 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 20:07:45.421414 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 20:07:45.421416 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     template = get_template(template_name, using=using)
[Sun Mar 24 20:07:45.421418 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 20:07:45.421421 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     return engine.get_template(template_name)
[Sun Mar 24 20:07:45.421423 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 20:07:45.421427 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 20:07:45.421429 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 20:07:45.421431 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     template, origin = self.find_template(template_name)
[Sun Mar 24 20:07:45.421433 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 20:07:45.421435 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 20:07:45.421437 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 20:07:45.421440 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 20:07:45.421442 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 20:07:45.421444 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 20:07:45.421446 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 20:07:45.421448 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     return parser.parse()
[Sun Mar 24 20:07:45.421450 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 20:07:45.421452 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 20:07:45.421454 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 20:07:45.421456 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 20:07:45.421460 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 20:07:45.421464 2019] [wsgi:error] [pid 1025:tid 140284357777152] [remote 127.0.0.1:39634] 
[Sun Mar 24 20:07:49.516838 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] Internal Server Error: /web/demo/
[Sun Mar 24 20:07:49.516856 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] Traceback (most recent call last):
[Sun Mar 24 20:07:49.516859 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
[Sun Mar 24 20:07:49.516861 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     compile_func = self.tags[command]
[Sun Mar 24 20:07:49.516863 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] KeyError: 'static'
[Sun Mar 24 20:07:49.516872 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] 
[Sun Mar 24 20:07:49.516874 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] During handling of the above exception, another exception occurred:
[Sun Mar 24 20:07:49.516876 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] 
[Sun Mar 24 20:07:49.516878 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] Traceback (most recent call last):
[Sun Mar 24 20:07:49.516880 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 20:07:49.516883 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     response = get_response(request)
[Sun Mar 24 20:07:49.516885 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 20:07:49.516887 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 20:07:49.516889 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 20:07:49.516891 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 20:07:49.516894 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/demo/views.py", line 40, in index
[Sun Mar 24 20:07:49.516896 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     return render(request, 'demo/name.html', {'results': context})
[Sun Mar 24 20:07:49.516898 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
[Sun Mar 24 20:07:49.516900 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Mar 24 20:07:49.516902 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
[Sun Mar 24 20:07:49.516904 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     template = get_template(template_name, using=using)
[Sun Mar 24 20:07:49.516907 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
[Sun Mar 24 20:07:49.516909 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     return engine.get_template(template_name)
[Sun Mar 24 20:07:49.516911 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
[Sun Mar 24 20:07:49.516913 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     return Template(self.engine.get_template(template_name), self)
[Sun Mar 24 20:07:49.516915 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
[Sun Mar 24 20:07:49.516917 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     template, origin = self.find_template(template_name)
[Sun Mar 24 20:07:49.516921 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
[Sun Mar 24 20:07:49.516923 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     template = loader.get_template(name, skip=skip)
[Sun Mar 24 20:07:49.516926 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
[Sun Mar 24 20:07:49.516928 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     contents, origin, origin.template_name, self.engine,
[Sun Mar 24 20:07:49.516930 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
[Sun Mar 24 20:07:49.516932 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     self.nodelist = self.compile_nodelist()
[Sun Mar 24 20:07:49.516934 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
[Sun Mar 24 20:07:49.516936 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     return parser.parse()
[Sun Mar 24 20:07:49.516938 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
[Sun Mar 24 20:07:49.516940 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     self.invalid_block_tag(token, command, parse_until)
[Sun Mar 24 20:07:49.516942 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/template/base.py", line 534, in invalid_block_tag
[Sun Mar 24 20:07:49.516945 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636]     "or load this tag?" % (token.lineno, command)
[Sun Mar 24 20:07:49.516948 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'static'. Did you forget to register or load this tag?
[Sun Mar 24 20:07:49.516952 2019] [wsgi:error] [pid 1025:tid 140284240279296] [remote 127.0.0.1:39636] 
[Sun Mar 24 20:38:30.673382 2019] [ssl:warn] [pid 956:tid 140120368049088] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 20:38:30.675653 2019] [ssl:warn] [pid 956:tid 140120368049088] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 20:38:30.687103 2019] [ssl:warn] [pid 1053:tid 140120368049088] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 20:38:30.687117 2019] [ssl:warn] [pid 1053:tid 140120368049088] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 21:16:36.531171 2019] [ssl:warn] [pid 965:tid 140412669074368] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 21:16:36.541175 2019] [ssl:warn] [pid 965:tid 140412669074368] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 21:16:36.558346 2019] [ssl:warn] [pid 1047:tid 140412669074368] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 21:16:36.558365 2019] [ssl:warn] [pid 1047:tid 140412669074368] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 21:36:35.408736 2019] [ssl:warn] [pid 973:tid 140260552518592] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 21:36:35.411690 2019] [ssl:warn] [pid 973:tid 140260552518592] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 21:36:35.423674 2019] [ssl:warn] [pid 1030:tid 140260552518592] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 21:36:35.423686 2019] [ssl:warn] [pid 1030:tid 140260552518592] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 21:38:47.574623 2019] [ssl:warn] [pid 987:tid 140192383306688] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 21:38:47.577607 2019] [ssl:warn] [pid 987:tid 140192383306688] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 21:38:47.589709 2019] [ssl:warn] [pid 1042:tid 140192383306688] AH01906: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Mar 24 21:38:47.589723 2019] [ssl:warn] [pid 1042:tid 140192383306688] AH01909: ec2-18-224-150-8.us-east-2.compute.amazonaws.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Mar 24 22:45:29.575495 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408] mod_wsgi (pid=3437): Target WSGI script '/opt/project_pegasus/django_sites/pegasus/pegasus/wsgi.py' cannot be loaded as Python module.
[Sun Mar 24 22:45:29.575659 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408] mod_wsgi (pid=3437): Exception occurred processing WSGI script '/opt/project_pegasus/django_sites/pegasus/pegasus/wsgi.py'.
[Sun Mar 24 22:45:29.579099 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408] Traceback (most recent call last):
[Sun Mar 24 22:45:29.579218 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "/opt/project_pegasus/django_sites/pegasus/pegasus/wsgi.py", line 16, in <module>
[Sun Mar 24 22:45:29.579233 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]     application = get_wsgi_application()
[Sun Mar 24 22:45:29.579254 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Sun Mar 24 22:45:29.579265 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]     django.setup(set_prefix=False)
[Sun Mar 24 22:45:29.579281 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
[Sun Mar 24 22:45:29.579291 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]     apps.populate(settings.INSTALLED_APPS)
[Sun Mar 24 22:45:29.579306 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
[Sun Mar 24 22:45:29.579316 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]     app_config = AppConfig.create(entry)
[Sun Mar 24 22:45:29.579331 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
[Sun Mar 24 22:45:29.579354 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]     mod = import_module(mod_path)
[Sun Mar 24 22:45:29.579371 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Sun Mar 24 22:45:29.579380 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]     return _bootstrap._gcd_import(name[level:], package, level)
[Sun Mar 24 22:45:29.579395 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Sun Mar 24 22:45:29.579411 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Sun Mar 24 22:45:29.579427 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
[Sun Mar 24 22:45:29.579443 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sun Mar 24 22:45:29.579459 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Sun Mar 24 22:45:29.579475 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Sun Mar 24 22:45:29.579491 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Sun Mar 24 22:45:29.579531 2019] [wsgi:error] [pid 3437] [remote 127.0.0.1:51408] ModuleNotFoundError: No module named 'polls'
[Sun Mar 24 22:52:21.778906 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51620] Not Found: /web/demo/demo/
[Sun Mar 24 22:52:52.496342 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51690] [DEBUG] Query: {}
[Sun Mar 24 22:52:52.496419 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51690] Result Count: 0
[Sun Mar 24 22:52:52.496439 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51690] Results: <QuerySet []>
[Sun Mar 24 22:52:52.496466 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51690] 
[Sun Mar 24 22:53:08.082609 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] [DEBUG] Query: {}
[Sun Mar 24 22:53:08.082684 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] Result Count: 0
[Sun Mar 24 22:53:08.082704 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] Results: <QuerySet []>
[Sun Mar 24 22:53:08.082727 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] 
[Sun Mar 24 22:53:12.265082 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] [DEBUG] Query: {'residence_type': 'house'}
[Sun Mar 24 22:53:12.265164 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] Result Count: 0
[Sun Mar 24 22:53:12.265189 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] Results: <QuerySet []>
[Sun Mar 24 22:53:12.265209 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51702] 
[Sun Mar 24 22:58:13.737445 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51832] [DEBUG] Query: {}
[Sun Mar 24 22:58:13.737526 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51832] Result Count: 0
[Sun Mar 24 22:58:13.737545 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51832] Results: <QuerySet []>
[Sun Mar 24 22:58:13.737564 2019] [wsgi:error] [pid 3681] [remote 127.0.0.1:51832] 
[Sun Mar 24 23:02:05.474757 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] Internal Server Error: /web/admin/demo/administrator/add/
[Sun Mar 24 23:02:05.474830 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] Traceback (most recent call last):
[Sun Mar 24 23:02:05.474841 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:02:05.474848 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = get_response(request)
[Sun Mar 24 23:02:05.474855 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:02:05.474878 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:02:05.474885 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:02:05.474891 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:02:05.474898 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 604, in wrapper
[Sun Mar 24 23:02:05.474904 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self.admin_site.admin_view(view)(*args, **kwargs)
[Sun Mar 24 23:02:05.474911 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Sun Mar 24 23:02:05.474917 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = view_func(request, *args, **kwargs)
[Sun Mar 24 23:02:05.474923 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[Sun Mar 24 23:02:05.474930 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = view_func(request, *args, **kwargs)
[Sun Mar 24 23:02:05.474936 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
[Sun Mar 24 23:02:05.474943 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return view(request, *args, **kwargs)
[Sun Mar 24 23:02:05.474949 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in add_view
[Sun Mar 24 23:02:05.474955 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self.changeform_view(request, None, form_url, extra_context)
[Sun Mar 24 23:02:05.474962 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
[Sun Mar 24 23:02:05.474968 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return bound_method(*args, **kwargs)
[Sun Mar 24 23:02:05.474974 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Sun Mar 24 23:02:05.474981 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = view_func(request, *args, **kwargs)
[Sun Mar 24 23:02:05.474987 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1525, in changeform_view
[Sun Mar 24 23:02:05.474994 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self._changeform_view(request, object_id, form_url, extra_context)
[Sun Mar 24 23:02:05.475000 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1564, in _changeform_view
[Sun Mar 24 23:02:05.475007 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self.save_model(request, new_object, form, not add)
[Sun Mar 24 23:02:05.475013 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1091, in save_model
[Sun Mar 24 23:02:05.475030 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     obj.save()
[Sun Mar 24 23:02:05.475036 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
[Sun Mar 24 23:02:05.475043 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     force_update=force_update, update_fields=update_fields)
[Sun Mar 24 23:02:05.475049 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
[Sun Mar 24 23:02:05.475056 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self._save_parents(cls, using, update_fields)
[Sun Mar 24 23:02:05.475062 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 772, in _save_parents
[Sun Mar 24 23:02:05.475068 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self._save_table(cls=parent, using=using, update_fields=update_fields)
[Sun Mar 24 23:02:05.475075 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 809, in _save_table
[Sun Mar 24 23:02:05.475081 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     for f in non_pks]
[Sun Mar 24 23:02:05.475087 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 809, in <listcomp>
[Sun Mar 24 23:02:05.475094 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     for f in non_pks]
[Sun Mar 24 23:02:05.475099 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 288, in pre_save
[Sun Mar 24 23:02:05.475106 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     file.save(file.name, file.file, save=False)
[Sun Mar 24 23:02:05.475112 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 87, in save
[Sun Mar 24 23:02:05.475119 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self.name = self.storage.save(name, content, max_length=self.field.max_length)
[Sun Mar 24 23:02:05.475125 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 49, in save
[Sun Mar 24 23:02:05.475132 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self._save(name, content)
[Sun Mar 24 23:02:05.475138 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 264, in _save
[Sun Mar 24 23:02:05.475144 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     fd = os.open(full_path, flags, 0o666)
[Sun Mar 24 23:02:05.475154 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/profile_pictures/Square-Profile-Pic-1-1_Bu9vXwc.jpg'
[Sun Mar 24 23:02:05.475174 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] 
[Sun Mar 24 23:02:05.475263 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] ERROR:django.request:Internal Server Error: /web/admin/demo/administrator/add/
[Sun Mar 24 23:02:05.475277 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] Traceback (most recent call last):
[Sun Mar 24 23:02:05.475285 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:02:05.475298 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = get_response(request)
[Sun Mar 24 23:02:05.475305 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:02:05.475312 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:02:05.475318 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:02:05.475325 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:02:05.475331 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 604, in wrapper
[Sun Mar 24 23:02:05.475337 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self.admin_site.admin_view(view)(*args, **kwargs)
[Sun Mar 24 23:02:05.475343 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Sun Mar 24 23:02:05.475350 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = view_func(request, *args, **kwargs)
[Sun Mar 24 23:02:05.475356 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[Sun Mar 24 23:02:05.475363 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = view_func(request, *args, **kwargs)
[Sun Mar 24 23:02:05.475369 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
[Sun Mar 24 23:02:05.475375 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return view(request, *args, **kwargs)
[Sun Mar 24 23:02:05.475381 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in add_view
[Sun Mar 24 23:02:05.475388 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self.changeform_view(request, None, form_url, extra_context)
[Sun Mar 24 23:02:05.475394 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
[Sun Mar 24 23:02:05.475400 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return bound_method(*args, **kwargs)
[Sun Mar 24 23:02:05.475406 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Sun Mar 24 23:02:05.475412 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     response = view_func(request, *args, **kwargs)
[Sun Mar 24 23:02:05.475419 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1525, in changeform_view
[Sun Mar 24 23:02:05.475425 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self._changeform_view(request, object_id, form_url, extra_context)
[Sun Mar 24 23:02:05.475431 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1564, in _changeform_view
[Sun Mar 24 23:02:05.475438 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self.save_model(request, new_object, form, not add)
[Sun Mar 24 23:02:05.475468 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1091, in save_model
[Sun Mar 24 23:02:05.475478 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     obj.save()
[Sun Mar 24 23:02:05.475484 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
[Sun Mar 24 23:02:05.475491 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     force_update=force_update, update_fields=update_fields)
[Sun Mar 24 23:02:05.475498 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
[Sun Mar 24 23:02:05.475505 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self._save_parents(cls, using, update_fields)
[Sun Mar 24 23:02:05.475512 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 772, in _save_parents
[Sun Mar 24 23:02:05.475519 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self._save_table(cls=parent, using=using, update_fields=update_fields)
[Sun Mar 24 23:02:05.475525 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 809, in _save_table
[Sun Mar 24 23:02:05.475532 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     for f in non_pks]
[Sun Mar 24 23:02:05.475539 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/base.py", line 809, in <listcomp>
[Sun Mar 24 23:02:05.475549 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     for f in non_pks]
[Sun Mar 24 23:02:05.475557 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 288, in pre_save
[Sun Mar 24 23:02:05.475563 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     file.save(file.name, file.file, save=False)
[Sun Mar 24 23:02:05.475570 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 87, in save
[Sun Mar 24 23:02:05.475577 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     self.name = self.storage.save(name, content, max_length=self.field.max_length)
[Sun Mar 24 23:02:05.475583 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 49, in save
[Sun Mar 24 23:02:05.475590 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     return self._save(name, content)
[Sun Mar 24 23:02:05.475596 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 264, in _save
[Sun Mar 24 23:02:05.475603 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956]     fd = os.open(full_path, flags, 0o666)
[Sun Mar 24 23:02:05.475612 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/profile_pictures/Square-Profile-Pic-1-1_Bu9vXwc.jpg'
[Sun Mar 24 23:02:05.475627 2019] [wsgi:error] [pid 4021] [remote 127.0.0.1:51956] 
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/PIL/Image.py", line 614, in __del__
NameError: name 'hasattr' is not defined
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/PIL/Image.py", line 614, in __del__
NameError: name 'hasattr' is not defined
[Sun Mar 24 23:18:23.923770 2019] [wsgi:error] [pid 4526] [remote 127.0.0.1:52420] [DEBUG] Query: {}
[Sun Mar 24 23:18:23.923878 2019] [wsgi:error] [pid 4526] [remote 127.0.0.1:52420] Result Count: 4
[Sun Mar 24 23:18:23.923909 2019] [wsgi:error] [pid 4526] [remote 127.0.0.1:52420] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:18:23.923945 2019] [wsgi:error] [pid 4526] [remote 127.0.0.1:52420] 
[Sun Mar 24 23:21:35.721405 2019] [wsgi:error] [pid 938] [remote 127.0.0.1:45496] [DEBUG] Query: {}
[Sun Mar 24 23:21:35.721512 2019] [wsgi:error] [pid 938] [remote 127.0.0.1:45496] Result Count: 4
[Sun Mar 24 23:21:35.721537 2019] [wsgi:error] [pid 938] [remote 127.0.0.1:45496] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:21:35.721571 2019] [wsgi:error] [pid 938] [remote 127.0.0.1:45496] 
[Sun Mar 24 23:24:23.455659 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45644] [DEBUG] Query: {}
[Sun Mar 24 23:24:23.455740 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45644] Result Count: 4
[Sun Mar 24 23:24:23.455754 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45644] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:24:23.455771 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45644] 
[Sun Mar 24 23:27:11.291976 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45712] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:27:11.292043 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45712] Result Count: 1
[Sun Mar 24 23:27:11.292058 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45712] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:27:11.292074 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45712] 
[Sun Mar 24 23:30:30.152459 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45744] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:30:30.152542 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45744] Result Count: 1
[Sun Mar 24 23:30:30.152568 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45744] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:30:30.152598 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45744] 
[Sun Mar 24 23:30:30.295215 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45744] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:30:38.656449 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45758] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:31:09.542066 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45770] Not Found: /web/media/
[Sun Mar 24 23:32:33.603867 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:32:33.603925 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800] Traceback (most recent call last):
[Sun Mar 24 23:32:33.603936 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:32:33.603941 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     response = get_response(request)
[Sun Mar 24 23:32:33.603962 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:32:33.603967 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:32:33.603971 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:32:33.603975 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:32:33.603979 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:32:33.603983 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     if fullpath.is_dir():
[Sun Mar 24 23:32:33.603986 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:32:33.603990 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:32:33.603994 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:32:33.603998 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     return self._accessor.stat(self)
[Sun Mar 24 23:32:33.604001 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:32:33.604007 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:32:33.604015 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:32:33.604028 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45800] 
[Sun Mar 24 23:33:24.778567 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:33:24.778626 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812] Traceback (most recent call last):
[Sun Mar 24 23:33:24.778636 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:33:24.778642 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     response = get_response(request)
[Sun Mar 24 23:33:24.778646 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:33:24.778651 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:33:24.778655 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:33:24.778659 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:33:24.778664 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:33:24.778668 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     if fullpath.is_dir():
[Sun Mar 24 23:33:24.778672 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:33:24.778677 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:33:24.778695 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:33:24.778700 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     return self._accessor.stat(self)
[Sun Mar 24 23:33:24.778704 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:33:24.778709 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:33:24.778717 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:33:24.778731 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45812] 
[Sun Mar 24 23:34:01.945529 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:34:01.945584 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816] Traceback (most recent call last):
[Sun Mar 24 23:34:01.945597 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:34:01.945604 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     response = get_response(request)
[Sun Mar 24 23:34:01.945611 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:34:01.945618 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:34:01.945624 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:34:01.945631 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:34:01.945637 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:34:01.945644 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     if fullpath.is_dir():
[Sun Mar 24 23:34:01.945651 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:34:01.945657 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:34:01.945664 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:34:01.945671 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     return self._accessor.stat(self)
[Sun Mar 24 23:34:01.945677 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:34:01.945684 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:34:01.945693 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:34:01.945711 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45816] 
[Sun Mar 24 23:34:19.631204 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:34:19.631262 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822] Traceback (most recent call last):
[Sun Mar 24 23:34:19.631272 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:34:19.631303 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     response = get_response(request)
[Sun Mar 24 23:34:19.631311 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:34:19.631317 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:34:19.631324 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:34:19.631330 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:34:19.631336 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:34:19.631342 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     if fullpath.is_dir():
[Sun Mar 24 23:34:19.631348 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:34:19.631354 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:34:19.631361 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:34:19.631366 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     return self._accessor.stat(self)
[Sun Mar 24 23:34:19.631371 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:34:19.631378 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:34:19.631389 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:34:19.631406 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45822] 
[Sun Mar 24 23:36:12.213670 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:36:12.213731 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888] Traceback (most recent call last):
[Sun Mar 24 23:36:12.213741 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:36:12.213747 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     response = get_response(request)
[Sun Mar 24 23:36:12.213751 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:36:12.213756 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:36:12.213760 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:36:12.213765 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:36:12.213771 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:36:12.213779 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     if fullpath.is_dir():
[Sun Mar 24 23:36:12.213807 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:36:12.213815 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:36:12.213820 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:36:12.213827 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     return self._accessor.stat(self)
[Sun Mar 24 23:36:12.213832 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:36:12.213838 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:36:12.213847 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:36:12.213859 2019] [wsgi:error] [pid 2162] [remote 127.0.0.1:45888] 
[Sun Mar 24 23:36:46.711132 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:36:46.711196 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892] Traceback (most recent call last):
[Sun Mar 24 23:36:46.711207 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:36:46.711212 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     response = get_response(request)
[Sun Mar 24 23:36:46.711218 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:36:46.711223 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:36:46.711227 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:36:46.711232 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:36:46.711239 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:36:46.711246 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     if fullpath.is_dir():
[Sun Mar 24 23:36:46.711253 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:36:46.711259 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:36:46.711265 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:36:46.711272 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     return self._accessor.stat(self)
[Sun Mar 24 23:36:46.711278 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:36:46.711284 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:36:46.711294 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:36:46.711316 2019] [wsgi:error] [pid 2776] [remote 127.0.0.1:45892] 
[Sun Mar 24 23:38:08.745149 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:38:08.745231 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948] Traceback (most recent call last):
[Sun Mar 24 23:38:08.745244 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:38:08.745251 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     response = get_response(request)
[Sun Mar 24 23:38:08.745256 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:38:08.745262 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:38:08.745269 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:38:08.745274 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:38:08.745278 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:38:08.745282 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     if fullpath.is_dir():
[Sun Mar 24 23:38:08.745286 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:38:08.745290 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:38:08.745294 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:38:08.745298 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     return self._accessor.stat(self)
[Sun Mar 24 23:38:08.745302 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:38:08.745305 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:38:08.745312 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:38:08.745322 2019] [wsgi:error] [pid 2835] [remote 127.0.0.1:45948] 
[Sun Mar 24 23:40:07.869036 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45976] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:40:07.869123 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45976] Result Count: 1
[Sun Mar 24 23:40:07.869140 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45976] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:40:07.869158 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45976] 
[Sun Mar 24 23:40:14.885421 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:40:14.885486 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] Result Count: 1
[Sun Mar 24 23:40:14.885499 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:40:14.885513 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] 
[Sun Mar 24 23:40:17.170719 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:40:17.170785 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] Result Count: 1
[Sun Mar 24 23:40:17.170802 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:40:17.170845 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:45982] 
[Sun Mar 24 23:44:39.168734 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:44:39.168797 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] Result Count: 1
[Sun Mar 24 23:44:39.168810 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:44:39.168824 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] 
[Sun Mar 24 23:44:40.861785 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:44:40.861858 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] Result Count: 1
[Sun Mar 24 23:44:40.861882 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:44:40.861912 2019] [wsgi:error] [pid 2980] [remote 127.0.0.1:46080] 
[Sun Mar 24 23:46:48.693200 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46166] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:46:48.693293 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46166] Result Count: 1
[Sun Mar 24 23:46:48.693315 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46166] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:46:48.693342 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46166] 
[Sun Mar 24 23:46:48.827308 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46166] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:46:57.965467 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46172] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Sun Mar 24 23:46:57.965547 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46172] Result Count: 1
[Sun Mar 24 23:46:57.965579 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46172] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Sun Mar 24 23:46:57.965605 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46172] 
[Sun Mar 24 23:46:58.159407 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46172] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:47:09.779944 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46182] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:47:22.164327 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46184] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:47:34.596860 2019] [core:error] [pid 3227] (13)Permission denied: [client 127.0.0.1:46186] AH00035: access to /media/demo/residence_pictures/3579_terrace_way_udQw3W4.png denied (filesystem path '/opt/project_pegasus/django_sites/pegasus/media/demo') because search permissions are missing on a component of the path
[Sun Mar 24 23:47:35.386800 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:47:35.386846 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186] Traceback (most recent call last):
[Sun Mar 24 23:47:35.386852 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:47:35.386860 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     response = get_response(request)
[Sun Mar 24 23:47:35.386865 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:47:35.386870 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:47:35.386874 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:47:35.386897 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:47:35.386905 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:47:35.386910 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     if fullpath.is_dir():
[Sun Mar 24 23:47:35.386916 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:47:35.386921 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:47:35.386926 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:47:35.386932 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     return self._accessor.stat(self)
[Sun Mar 24 23:47:35.386937 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:47:35.386943 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:47:35.386951 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:47:35.386964 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46186] 
[Sun Mar 24 23:47:47.280169 2019] [core:error] [pid 3203] (13)Permission denied: [client 127.0.0.1:46190] AH00035: access to /media/demo/residence_pictures/3579_terrace_way_udQw3W4.png denied (filesystem path '/opt/project_pegasus/django_sites/pegasus/media/demo') because search permissions are missing on a component of the path
[Sun Mar 24 23:47:48.042332 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:47:48.042380 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190] Traceback (most recent call last):
[Sun Mar 24 23:47:48.042386 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Sun Mar 24 23:47:48.042394 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     response = get_response(request)
[Sun Mar 24 23:47:48.042398 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Sun Mar 24 23:47:48.042403 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     response = self.process_exception_by_middleware(e, request)
[Sun Mar 24 23:47:48.042406 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Sun Mar 24 23:47:48.042410 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Mar 24 23:47:48.042414 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Sun Mar 24 23:47:48.042418 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     if fullpath.is_dir():
[Sun Mar 24 23:47:48.042422 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Sun Mar 24 23:47:48.042426 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     return S_ISDIR(self.stat().st_mode)
[Sun Mar 24 23:47:48.042430 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Sun Mar 24 23:47:48.042450 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     return self._accessor.stat(self)
[Sun Mar 24 23:47:48.042454 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Sun Mar 24 23:47:48.042458 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190]     return strfunc(str(pathobj), *args)
[Sun Mar 24 23:47:48.042464 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Sun Mar 24 23:47:48.042473 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46190] 
[Sun Mar 24 23:47:59.180186 2019] [wsgi:error] [pid 3201] [remote 127.0.0.1:46194] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:48:56.831292 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46198] [DEBUG] Query: {}
[Sun Mar 24 23:48:56.831374 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46198] Result Count: 4
[Sun Mar 24 23:48:56.831391 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46198] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:48:56.831410 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46198] 
[Sun Mar 24 23:48:57.019263 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46198] Not Found: /web/demo/media/demo/residence_pictures/69_michael_way_2lj5lMn.png
[Sun Mar 24 23:48:57.032308 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46204] Not Found: /web/demo/media/demo/residence_pictures/2134_green_st_b1HfuRC.png
[Sun Mar 24 23:48:57.041609 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46206] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:48:57.049974 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46202] Not Found: /web/demo/media/demo/residence_pictures/135_mendosa_ave_XaUZQeX.png
[Sun Mar 24 23:49:05.612928 2019] [wsgi:error] [pid 3253] [remote 127.0.0.1:46208] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:50:05.159468 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] [DEBUG] Query: {}
[Sun Mar 24 23:50:05.159548 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] Result Count: 4
[Sun Mar 24 23:50:05.159563 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:50:05.159579 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] 
[Sun Mar 24 23:50:05.410431 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46224] Not Found: /web/demo/media/demo/residence_pictures/2134_green_st_b1HfuRC.png
[Sun Mar 24 23:50:05.414348 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:50:05.429794 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46220] Not Found: /web/demo/media/demo/residence_pictures/69_michael_way_2lj5lMn.png
[Sun Mar 24 23:50:05.430970 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46222] Not Found: /web/demo/media/demo/residence_pictures/135_mendosa_ave_XaUZQeX.png
[Sun Mar 24 23:50:07.958736 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] [DEBUG] Query: {}
[Sun Mar 24 23:50:07.958807 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] Result Count: 4
[Sun Mar 24 23:50:07.958836 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:50:07.958892 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] 
[Sun Mar 24 23:50:08.091697 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46224] Not Found: /web/demo/media/demo/residence_pictures/135_mendosa_ave_XaUZQeX.png
[Sun Mar 24 23:50:08.101925 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46222] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:50:08.102102 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46210] Not Found: /web/demo/media/demo/residence_pictures/2134_green_st_b1HfuRC.png
[Sun Mar 24 23:50:08.107010 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46220] Not Found: /web/demo/media/demo/residence_pictures/69_michael_way_2lj5lMn.png
[Sun Mar 24 23:50:20.029058 2019] [wsgi:error] [pid 3299] [remote 127.0.0.1:46234] Not Found: /web/demo/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Sun Mar 24 23:54:12.602641 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46246] [DEBUG] Query: {}
[Sun Mar 24 23:54:12.602732 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46246] Result Count: 4
[Sun Mar 24 23:54:12.602758 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46246] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:54:12.602790 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46246] 
[Sun Mar 24 23:57:55.931321 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46316] [DEBUG] Query: {}
[Sun Mar 24 23:57:55.931396 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46316] Result Count: 4
[Sun Mar 24 23:57:55.931414 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46316] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Sun Mar 24 23:57:55.931436 2019] [wsgi:error] [pid 3425] [remote 127.0.0.1:46316] 
[Mon Mar 25 00:23:31.513961 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Mon Mar 25 00:23:31.514021 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866] Traceback (most recent call last):
[Mon Mar 25 00:23:31.514028 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Mon Mar 25 00:23:31.514036 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     response = get_response(request)
[Mon Mar 25 00:23:31.514041 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Mon Mar 25 00:23:31.514045 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     response = self.process_exception_by_middleware(e, request)
[Mon Mar 25 00:23:31.514050 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Mon Mar 25 00:23:31.514054 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Mar 25 00:23:31.514059 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Mon Mar 25 00:23:31.514064 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     if fullpath.is_dir():
[Mon Mar 25 00:23:31.514068 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Mon Mar 25 00:23:31.514072 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     return S_ISDIR(self.stat().st_mode)
[Mon Mar 25 00:23:31.514092 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Mon Mar 25 00:23:31.514096 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     return self._accessor.stat(self)
[Mon Mar 25 00:23:31.514100 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Mon Mar 25 00:23:31.514104 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866]     return strfunc(str(pathobj), *args)
[Mon Mar 25 00:23:31.514113 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Mon Mar 25 00:23:31.514135 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46866] 
[Mon Mar 25 00:23:42.101322 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872] Internal Server Error: /web/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png
[Mon Mar 25 00:23:42.101376 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872] Traceback (most recent call last):
[Mon Mar 25 00:23:42.101383 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
[Mon Mar 25 00:23:42.101388 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     response = get_response(request)
[Mon Mar 25 00:23:42.101392 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
[Mon Mar 25 00:23:42.101396 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     response = self.process_exception_by_middleware(e, request)
[Mon Mar 25 00:23:42.101401 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
[Mon Mar 25 00:23:42.101405 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Mar 25 00:23:42.101409 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/opt/project_pegasus/django_sites/pegasus/venv/lib/python3.6/site-packages/django/views/static.py", line 37, in serve
[Mon Mar 25 00:23:42.101413 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     if fullpath.is_dir():
[Mon Mar 25 00:23:42.101417 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/usr/lib/python3.6/pathlib.py", line 1348, in is_dir
[Mon Mar 25 00:23:42.101421 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     return S_ISDIR(self.stat().st_mode)
[Mon Mar 25 00:23:42.101427 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/usr/lib/python3.6/pathlib.py", line 1158, in stat
[Mon Mar 25 00:23:42.101432 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     return self._accessor.stat(self)
[Mon Mar 25 00:23:42.101438 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
[Mon Mar 25 00:23:42.101444 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872]     return strfunc(str(pathobj), *args)
[Mon Mar 25 00:23:42.101453 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872] PermissionError: [Errno 13] Permission denied: '/opt/project_pegasus/django_sites/pegasus/media/demo/residence_pictures/3579_terrace_way_udQw3W4.png'
[Mon Mar 25 00:23:42.101466 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46872] 
[Mon Mar 25 00:24:39.630490 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46896] [DEBUG] Query: {}
[Mon Mar 25 00:24:39.630565 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46896] Result Count: 4
[Mon Mar 25 00:24:39.630595 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46896] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Mon Mar 25 00:24:39.630658 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:46896] 
[Mon Mar 25 00:52:43.248482 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47364] [DEBUG] Query: {}
[Mon Mar 25 00:52:43.248554 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47364] Result Count: 4
[Mon Mar 25 00:52:43.248576 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47364] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 69 Michael Way, Santa Clara, CA 95051>, <Domicile: 135 Mendosa Ave, San Francisco, CA 94116>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Mon Mar 25 00:52:43.248605 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47364] 
[Mon Mar 25 00:52:51.452625 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47374] [DEBUG] Query: {'residence_type': 'apartment'}
[Mon Mar 25 00:52:51.452690 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47374] Result Count: 2
[Mon Mar 25 00:52:51.452711 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47374] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Mon Mar 25 00:52:51.452735 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47374] 
[Mon Mar 25 00:53:23.626429 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47378] [DEBUG] Query: {'residence_type': 'apartment'}
[Mon Mar 25 00:53:23.626493 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47378] Result Count: 2
[Mon Mar 25 00:53:23.626508 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47378] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>, <Domicile: 2134 Green St. Apt #6, San Francisco, CA 94123>]>
[Mon Mar 25 00:53:23.626523 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47378] 
[Mon Mar 25 00:53:30.612320 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47398] [DEBUG] Query: {'residence_type': 'apartment', 'pet_friendly': True}
[Mon Mar 25 00:53:30.612393 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47398] Result Count: 1
[Mon Mar 25 00:53:30.612415 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47398] Results: <QuerySet [<Domicile: 3579 Terrace Way Apt. #33, Lafayette, CA 94549>]>
[Mon Mar 25 00:53:30.612441 2019] [wsgi:error] [pid 4249] [remote 127.0.0.1:47398] 
